package org.poptarticus.punsAd.Books;

import java.util.Random;


public class factbook {

    public String[] mFact = {
            "Ants stretch when they wake up in the morning.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Google hired a camel to create the Street View of a desert.",
            "Mobile phones have 18 times more bacteria than toilet handles.",
            "Krusty the Clown was originally created to be Homer Simpsons secret identity.",
            "Lady Gaga once baught $1000 worth of pizza for fans waiting in line for her.",
            "The puppeteers who animated the raptors in 'Jurassic Park' had to take a 6 week long class on how to move like a dinosaur.",
            "There's town in Texas called Earth and it's the only place on Earth officially named Earth.",
            "You could cover the Great Wall of China 8 times Nutella sold in a year.",
            "The famous Windows start up sound was composed using a Mac.",
            "Oxford University is older than the Aztec Empire.",
            "Blue whales are so enormmous that a small child could swim through it's veins.",
            "A pound of houseflies contains more protein as compared to a pound of beef.",
            "More people speak English in China than the United States.",
            "In space, you cannot cry because there is no gravity to make the tears flow.",
            "Man is the only mammal that willingly delays sleep.",
            "Male kangaroos flex their biceps to impress females.",
            "IN Australia Burger King is called Hungry Jacks.",
            "A group of pandas is called an embarrassment.",
            "The U.S. Government spent $277,000 on pickle research in 1993.",
            "A new study suggests that eating chocolate could improve the brain's ability to do Mathematics.",
            "It rains diamonds on Saturn and Jupiter", "Will Smith's first name is actually Willard, not William",
            "The Walking Dead cast and crew holds death dinner's for any characters who get killed off the show",
            "THe bio-Bus is a bus service in the UK that is powered by poop",
            "There's a law in South Korea that bans under 16s from playing online games between midnight and 6am, called the 'Shutdown Law'.",
            "The chills you get when you listen to music is called musical frission.",
            "At YouTube Headquarters, employees can either take the elevator, stairs or slide.",
            "Rat's can't throw up' that's why rat poison works.",
            "Most of the dust underneath your bed is actually your own dead skin.",
            "In Mexico, artists can pay their taxes with artwork",
            "Marge Simpson was originally supposed to have bunny ears underneath her blue hair",
            "Google hired a camel to create the Street View of a desert",
            "Banging your head against a wall burns 150 calories an hour.",
            "In the UK, it is illegal to eat mince pies on Christmas Day!",
            "Pteronophobia is the fear of being tickled by feathers!",
            "When hippos are upset, their sweat turns red.",
            "A flock of crows is known as a murder.",
            "Facebook Addiction Disorder is a mental disorder identified by Psychologists.",
            "The average woman uses her height in lipstick every 5 years.",
            "29th May is officially Put a Pillow on Your Fridge Day.",
            "Cherophobia is the fear of fun.",
            "Human saliva has a boiling point three times that of regular water.",
            "If you lift a kangaroos tail off the ground it cant hop.",
            "Hyphephilia are people who get aroused by touching fabrics.",
            "The person who invented the Frisbee was cremated and made into frisbees after he died!"
            , "During your lifetime, you will produce enough saliva to fill two swimming pools.",
            "An eagle can kill a young deer and fly away with it.",
            "Polar bears can eat as many as 86 penguins in a single sitting.",
            "King Henry VIII slept with a gigantic axe beside him.",
            "Bikinis and tampons invented by men.",
            "If Pinokio says My Noes Will Grow Now, it would cause a paradox. Details here.",
            "Heart attacks are more likely to happen on a Monday.",
            "If you consistently fart for 6 years & 9 months, enough gas is produced to create the energy of an atomic bomb!",
            "An average persons yearly fast food intake will contain 12 pubic hairs.",
            "The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk!",
            "There is a species of spider called the Hobo Spider.",
            "A toaster uses almost half as much energy as a full-sized oven.",
            "A baby spider is called a spiderling.",
            "You cannot snore and dream at the same time.",
            "The following can be read forward and backwards: Do geese see God?",
            "A baby octopus is about the size of a flea when it is born.",
            "A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
            "In Uganda, 50% of the population is under 15 years of age.",
            "Hitlers mother considered abortion but the doctor persuaded her to keep the baby.",
            "Arab women can initiate a divorce if their husbands dont pour coffee for them.",
            "Recycling one glass jar saves enough energy to watch TV for 3 hours.",
            "Smearing a small amount of dog feces on an insect bite will relieve the itching and swelling.",
            "Catfish are the only animals that naturally have an odd number of whiskers.",
            "Facebook, Skype and Twitter are all banned in China."
            , "95% of people text things they could never say in person.",
            "The Titanic was the first ship to use the SOS signal.",
            "About 8,000 Americans are injured by musical instruments each year.",
            "The French language has seventeen different words for surrender.",
            "Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
            "Bob Dylans real name is Robert Zimmerman.",
            "A crocodile cant poke its tongue out :p",
            "Sea otters hold hands when they sleep so they dont drift away from each other.",
            "A small child could swim through the veins of a blue whale.",
            "Bin Ladens death was announced on 1st May 2011. Hitlers death was announced on 1st May 1945."

    };

}
