package org.poptarticus.punsAd.Books;

/**
 * Created by aaron on 12/4/2016.
 */

public class iceBreakerbook {

    // Member variable (properties about the object)
    public String[] mIcebreaker = {

            "Whats the greatest bit of advice a parent or mentor has given you?",
            "What technology innovation made the most impact on your life?",
            "Describe a challenging situation youve been in and tell how you resolved it?",
            "How would you spend one million dollars?",
            "Who is your hero, and why?",
            "Tell us your earliest childhood memory.",
            "Who was your favorite teacher in school and how did s/he impact you?",
            "If you could choose an age to remain forever, which age would you choose?",
            "What is one important skill every person should have?",
            "What is your favorite sport to watch?",
            "If you had one free hour each day, how would you use it?",
            "What was the best thing that happened to you this weekend? This month? This year?",
            "If you could go anywhere in the world on vacation, where would you go?",
            "How would your friends describe you?",
            "What would be the ultimate gift for you to receive?",
            "If you could live anywhere in the world, where would it be?",
            "Would you rather be invisible or be able to read minds?",
            "If you had a time machine, what point in the past or future would you visit?",
            "Name two things you consider yourself to be very good at.",
            "If you could live in any period of history, when would it be?",
            "Whats the greatest bit of advice a parent or mentor has given you?",
            "What technology innovation made the most impact on your life?",
            "Describe a challenging situation youve been in and tell how you resolved it?",
            "How would you spend one million dollars?",
            "Who is your hero, and why?",
            "Tell us your earliest childhood memory.",
            "Who was your favorite teacher in school and how did s/he impact you?",
            "If you could choose an age to remain forever, which age would you choose?",
            "What is one important skill every person should have?",
            "What is your favorite sport to watch?",
            "If you had one free hour each day, how would you use it?",
            "What was the best thing that happened to you this weekend? This month? This year?",
            "If you could go anywhere in the world on vacation, where would you go?",
            "How would your friends describe you?",
            "What would be the ultimate gift for you to receive?",
            "If you could live anywhere in the world, where would it be?",
            "Would you rather be invisible or be able to read minds?",
            "If you had a time machine, what point in the past or future would you visit?",
            "Name two things you consider yourself to be very good at.",
            "If you could live in any period of history, when would it be?",
            "What is the best perk that you have had at a job?",
            "Describe one experience youve had where you took a huge leap of faith.",
            "What is the best vacation youve ever had?",
            "Where in the world have you been that you thought was paradise?",
            "What is the meaning of your name?",
            "If you could host a talk show, who would be your first guest?",
            "What is one word that you would use to describe your team?",
            "Share a personal fact no one would ever guess about you.",
            "What is the most important personal attribute that you bring to your job?",
            "What is one thing you admire most about the person to the right of you?",
            "What would you like to be known for?",
            "What fictional place would you like to visit?",
            "Share a funny incident in your life.",
            "What is your favorite outdoor activity?",
            "Who would you like to exchange roles with?",
            "What is one of the things on your bucket list?",
            "Describe yourself in 3 words.",
            "What do you enjoy doing to relieve stress?",
            "If you were famous, what would you be famous for?",
            "What do you think you will be doing 20 years from now?",
            "If you didnt need a job, were healthy, and had plenty of time, what would you do?",
            "What do you consider your greatest achievement?",
            "What is a recent book that you have enjoyed? Why?",
            "What would you do with your 15 minutes of fame?",
            "Over the course of your life, how many cities have you lived in and which was your favorite?",
            "What was going on during the happiest time of your life?",
            "If you could only take one physical item with you on a deserted island, what it would be?",
            "Whats one sentence youd like to hear from your boss?",
            "If you could have a dinner with someone who is alive or dead, who would it be and why?",
            "What are you going to do when you retire?"

    };
}
